# Generated by Django 2.1 on 2018-08-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'street'), (1, 'dom'), (2, 'kw'), (3, 'ls')])),
            ],
        ),
        migrations.CreateModel(
            name='Doma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField()),
                ('bukva', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'doma',
                'ordering': ['nomer', 'bukva'],
            },
        ),
        migrations.CreateModel(
            name='Kws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField()),
                ('bukva', models.CharField(max_length=10)),
                ('dom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Address.Doma')),
            ],
            options={
                'verbose_name_plural': 'kws',
                'ordering': ['nomer', 'bukva'],
            },
        ),
        migrations.CreateModel(
            name='Ls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField()),
                ('fio', models.CharField(max_length=200)),
                ('kw', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Address.Kws')),
            ],
            options={
                'verbose_name_plural': 'lss',
                'ordering': ['nomer', 'fio'],
            },
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'streets',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='doma',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Address.Streets'),
        ),
    ]
